//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNotesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesCollabe
    {
        public int Id { get; set; }
        public int Note_id { get; set; }
        public int UserId { get; set; }
        public string Permission { get; set; }
    }
}
